site_name: Eldo Eletrostática
site_description: Documentação do projeto Eldo Eletrostática
repo_url: https://github.com/Eldo-Eletrostatica/Documentacao
repo_name: Eldo-Eletrostatica/Documentacao

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Início: index.md
  - Requisitos: historias_usuários.md
  - Processo:
      - Quadro Kanban: processo/quadro-kanban.md
      - Critérios de Aceite: processo/criterios-aceite.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
