site_name: Eudo Eletrostática
site_description: Documentação do projeto Eudo Eletrostática
repo_url: https://github.com/Eudo-Eletrostatica/Documentacao
repo_name: Eudo-Eletrostatica/Documentacao

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para tema claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Início: index.md
  - Requisitos: historias_usuários.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
